version: '2'

services:
  php54:
    build:
        context: .
        dockerfile: docker/Dockerfile-php54

  php55:
    build:
        context: .
        dockerfile: docker/Dockerfile-php55

  php56:
    build:
        context: .
        dockerfile: docker/Dockerfile-php56

  php70:
    build:
        context: .
        dockerfile: docker/Dockerfile-php70

  php71:
    build:
        context: .
        dockerfile: docker/Dockerfile-php71

  hhvm:
    build:
      context: .
      dockerfile: docker/Dockerfile-hhvm
