FROM jolicode/php54:latest

ENV SRC_DIR /usr/src/gaufrette
WORKDIR ${SRC_DIR}/

RUN sudo apt-get update && \
    sudo apt-get install -y libssh2-1-dev && \
    sudo rm -rf /var/lib/apt/lists/* && \
    pecl install mongo ssh2

COPY composer.json ${SRC_DIR}/
RUN sudo chown -R travis ${SRC_DIR} && \
    composer global require hirak/prestissimo && \
    composer install --prefer-dist && \
    rm -rf ~/.composer/cache/*

VOLUME ${SRC_DIR}/vendor

COPY . ${SRC_DIR}/
RUN sudo chown -R travis ${SRC_DIR}

CMD "${SRC_DIR}/bin/tests"
