FROM ubuntu:precise

RUN apt-get update && \
    apt-get install -y --no-install-recommends openssh-server && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd && \
    useradd -d /home/gaufrette gaufrette && \
    mkdir /home/gaufrette && \
    chown gaufrette:gaufrette /home/gaufrette && \
    echo "gaufrette:gaufrette" | chpasswd

CMD ["/usr/sbin/sshd", "-D"]
