---
name: Roave

on: workflow_call

jobs:
  roave_bc_check:
    name: BC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Composer install
        run: composer require --dev roave/backward-compatibility-check
      - name: Roave BC Check
        run: vendor/bin/roave-backward-compatibility-check --format=github-actions
