on: [push, pull_request]
name: Static analysis

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        run:
          - { packages: 'league/flysystem:^1.0' }
          - { packages: 'league/flysystem:^2.0' }
          - { packages: 'league/flysystem:^3.0' }
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mongo, mbstring, fileinfo
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies and run php-stan
        run: |
          make require-common
          composer require ${{ matrix.run.packages }} --no-update
          composer require --dev --no-update phpstan/phpstan:1.8.8
          composer update --no-interaction --prefer-dist

      - name: PHPStan
        run: |
          ./vendor/bin/phpstan --version
          ./vendor/bin/phpstan analyse


  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mongo, mbstring, fileinfo
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          make require-all
          composer update --no-interaction --prefer-dist

      - name: PHP-CS-Fixer
        run: |
          ./vendor/bin/php-cs-fixer --version
          ./vendor/bin/php-cs-fixer fix --diff --dry-run --show-progress=none

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        run:
          - { php: '7.4', packages: 'league/flysystem:^1.0' }
          - { php: '7.4', packages: 'league/flysystem:^2.0' }
          - { php: '8.1', packages: 'league/flysystem:^3.0' }
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.run.php }}
          extensions: mongo, mbstring, fileinfo, simplexml
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          make require-common
          composer require --dev --no-update psalm/phar:4.9.2 ${{ matrix.run.packages }}
          composer update --no-interaction --prefer-dist

      - name: Psalm
        run: |
          ./vendor/bin/psalm.phar --version
          ./vendor/bin/psalm.phar --output-format=github --no-progress --stats
